name: CI test to run SCM ccpp_prebuild script

on: [push, pull_request]

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - name: Checkout current ccpp-physics code
      uses: actions/checkout@v2

    - name: Get repository information from current ccpp-physics code
      run: |
        GIT_REMOTE=`git remote get-url origin` && export GIT_REMOTE
        GIT_REMOTE_HASH=`git rev-parse HEAD` && export GIT_REMOTE_HASH
        GIT_REMOTE_BRANCH=`git rev-parse --abbrev-ref HEAD` && export GIT_REMOTE_BRANCH

    - name: Checkout latest ccpp-scm code
      run: |
        git clone https://github.com/NCAR/ccpp-scm.git
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/ccpp/physics
        pwd
        ls
        git remote 
        git remote -v

    - name: Initialize submodules
      run: |
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/
        git submodule update --init --recursive
        cd ccpp/physics
        git remote add remote_local $GIT_REMOTE
        git fetch $GIT_REMOTE
        git checkout $GIT_REMOTE/$GIT_BRANCH
        git remote -v
    
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Run ccpp_prebuild.py
      run: |
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/
        mkdir -p /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/scm/bin/ccpp/physics/physics/
        ./ccpp/framework/scripts/ccpp_prebuild.py --config ccpp/config/ccpp_prebuild_config.py