name: CI test to run SCM ccpp_prebuild script

on: [push, pull_request]

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - name: Checkout current ccpp-physics code
      uses: actions/checkout@v2

    - name: Update checkout
      run: |
        pwd
        ls
        git status
        git remote -v
        GIT_REMOTE=`git remote get-url origin` && export GIT_REMOTE

    - name: Checkout latest ccpp-scm code
      run: |
        git clone https://github.com/NCAR/ccpp-scm.git
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/ccpp/physics
        pwd
        ls
        git status
        git remote -v
        echo $GIT_REMOTE

    - name: Initialize submodules
      run: |
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/
        git submodule update --init --recursive
    
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Run ccpp_prebuild.py
      run: |
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/
        mkdir -p /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/scm/bin/ccpp/physics/physics/
        ./ccpp/framework/scripts/ccpp_prebuild.py --config ccpp/config/ccpp_prebuild_config.py