name: CI test to run SCM ccpp_prebuild script

on: [push, pull_request]

env:
  GIT_REMOTE_URL: https://github.com/NCAR/ccpp-physics.git
  GIT_REMOTE_HASH: 255035269760c1a6560317c400727d962cdc57f0
  GIT_REMOTE_NAME: origin
  GIT_REMOTE_BRANCH: main

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - name: Checkout current ccpp-physics code
      uses: actions/checkout@v2
      run: echo "GIT_REMOTE=`git remote get-url origin` >> $GIT_REMOTE_URL

    - name: Checkout latest ccpp-scm code
      run: |
        git clone https://github.com/NCAR/ccpp-scm.git

    - name: Initialize submodules
      run: |
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/ccpp/physics
        git remote add remote_local $GIT_REMOTE_NAME
        git fetch $GIT_REMOTE_NAME
        git checkout $GIT_REMOTE_NAME/$GIT_REMOTE_BRANCH
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm
        git submodule update --init --recursive
        git remote -v
    
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Run ccpp_prebuild.py
      run: |
        cd /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/
        mkdir -p /home/runner/work/ccpp-physics/ccpp-physics/ccpp-scm/scm/bin/ccpp/physics/physics/
        ./ccpp/framework/scripts/ccpp_prebuild.py --config ccpp/config/ccpp_prebuild_config.py